all:
	@echo "Please READ Tutorial 1 and don't build the tutorials yourself ! Use CMake instead. If you have a problem, read the FAQ"

CXXFLAGS = -I /usr/local/include -I /usr/local/include/GLFW -I..
LDFLAGS = -L /usr/local/lib -lglew -lglfw3 -framework opengl ../common/shader.cpp
